### ISSUE TITLE
Show both header and block sync status 

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/ergo-node-interface#2]
A new node is doing synchronisation headers and blocks in parallel:
1) Headers synchronisation usually starts first
2) Blocks synchronisation can happen in parallel following headers sync.

Each status better be reported separately and for each maximum processed `height` (block number) should be shown. (as `Current height` value)

Subtasks:
- [ ]  show  "Synchronized Header" when headers are syncing and current header height is updated
- [ ] show "Syncronized Block" while blocks are syncing and current block height is updated
- [ ] `Best block id` show as url to explorer which open the block page in a new tab.

**Comment by kushti** [comment]
Make progress bar for sync also
