### ISSUE TITLE
Render error message in case of a wallet error

### ISSUE THREAD

**Issue by pragmaxim** [ergoplatform/ergo-node-interface#34]
Hi, there is this nasty issue https://github.com/ergoplatform/ergo/issues/1398 when node-syncing gets stuck and users report it without any logs. I added an `error` field into the response, if it is not empty string, it means some error happened at some background process and it will most likely be the reason of the syncing process being stuck. It would be cool to make it part of the dashboard.

I have no JS/react experience, help appreciated.

**Comment by deadit** [comment]
Hey, sorry for the late answer. Will be on the next node version, I think

![image](https://user-images.githubusercontent.com/26635501/139870512-b5092f07-37dd-4e58-898d-d0931224e9bb.png)
