### ISSUE TITLE
Wallet UI improvements [aggregate issue]

### ISSUE THREAD

**Issue by aslesarenko** [ergoplatform/ergo-node-interface#7]
Change messages:
- [x] 1) “You need to initializer your wallet to access wallet UI.”
- [x] 2) “API key is set successfully”
- [x] 3) “The wallet UI is locked. You need to unlock the wallet to access its UI.
- [x] 4) "Your wallet is locked successfully"

The buttons on top look confusing.
- [ ] 1) They should be placed inside the Wallet screen.
- [x] 2) If they cannot be clicked, they shouldn't look like buttons.
- [x] 3) use status colors: 
          - red - uninitialised wallet
          - amber - locked wallet
          - green - active wallet

**Comment by deadit** [comment]
Updated.
